### ISSUE TITLE
Number of threads seems not correct

### ISSUE THREAD

**Issue by QiaoLei-88** [QiaoLei-88/NSolver#19]

**Comment by QiaoLei-88** [comment]
The extra thread is created by MPI library:

(gdb) bt
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:84
#1  0x00007fffed72ff70 in do_clone (pd=0x7fffe27e3700, attr=0x7fffed73a880, stackaddr=<optimized out>, stopped=1,
    fct=0x7fffed730dc0 <start_thread>, clone_flags=4001536) at ../nptl/sysdeps/pthread/createthread.c:75
#2  0x00007fffed7318ba in create_thread (stackaddr=<optimized out>, attr=0x7fffed73a880, pd=0x7fffe27e3700)
    at ../nptl/sysdeps/pthread/createthread.c:212
#3  __pthread_create_2_1 (newthread=0x7fffed15cf40, attr=0x0, start_routine=0x7fffecec69d0 <orte_progress_thread_engine>,
    arg=0x7fffed15cf20) at pthread_create.c:566
#4  0x00007fffecbc7c86 in opal_thread_start () from /u/qiaolei/Library/openmpi-1.8.1/lib/libopen-pal.so.6
#5  0x00007fffecec6eca in orte_ess_base_app_setup () from /u/qiaolei/Library/openmpi-1.8.1/lib/libopen-rte.so.7
#6  0x00007fffecec9be7 in rte_init () from /u/qiaolei/Library/openmpi-1.8.1/lib/libopen-rte.so.7
#7  0x00007fffece93c94 in orte_init () from /u/qiaolei/Library/openmpi-1.8.1/lib/libopen-rte.so.7
#8  0x00007ffff7959772 in ompi_mpi_init () from /u/qiaolei/Library/mpi/lib/libmpi.so.1
#9  0x00007ffff7979996 in PMPI_Init_thread () from /u/qiaolei/Library/mpi/lib/libmpi.so.1
#10 0x00007ffff4b9d761 in dealii::Utilities::MPI::MPI_InitFinalize::MPI_InitFinalize (this=0x7fffffffe5af,
    argc=@0x7fffffffd7fc: 1, argv=@0x7fffffffd7f0: 0x7fffffffe6a8, max_num_threads=1)
    at /u/qiaolei/devel/deal.II/dealii/source/base/mpi.cc:359
#11 0x0000000000427bba in main (argc=1, argv=0x7fffffffe6a8)
    at /u/qiaolei/devel/deal.II/dealii/examples/step-40/step-40.cc:705
